default_config:

logger:
  default: info
  logs:
    custom_components.glocaltokens: debug
# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
